name: mongos
services: 
  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27017:27017
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
  mongo2:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - 27018:27017
    volumes:
      - "mongo2_data:/data/db"
      - "mongo2_config:/data/configdb"
  mongosetup:
    image: mongo:7.0
    depends_on:
      - mongo1
      - mongo2
    volumes:
      - ./mongodb/scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/init.sh"]
volumes:
  mongo1_data:
  mongo1_config:
  mongo2_data:
  mongo2_config: